export const PHASE = [
  { type: "ban", team: "blue", duration: 3 },
  { type: "ban", team: "red", duration: 3 },
  { type: "ban", team: "blue", duration: 3 },
  { type: "ban", team: "red", duration: 3 },
  { type: "ban", team: "blue", duration: 3 },
  { type: "ban", team: "red", duration: 3 },
  { type: "pick", team: "blue", duration: 3 },
  { type: "pick", team: "red", duration: 3 },
  { type: "pick", team: "red", duration: 3 },
  { type: "pick", team: "blue", duration: 3 },
  { type: "pick", team: "blue", duration: 3 },
  { type: "pick", team: "red", duration: 3 },
  { type: "ban", team: "red", duration: 3 },
  { type: "ban", team: "blue", duration: 3 },
  { type: "ban", team: "red", duration: 3 },
  { type: "ban", team: "blue", duration: 3 },
  { type: "pick", team: "red", duration: 3 },
  { type: "pick", team: "blue", duration: 3 },
  { type: "pick", team: "blue", duration: 3 },
  { type: "pick", team: "red", duration: 3 },
  { type: "swap", team: "both", duration: 5 },
];
