export const PHASE = [
  { type: "ban", team: "blue", duration: 3, index: 0 },
  { type: "ban", team: "red", duration: 3, index: 0 },
  { type: "ban", team: "blue", duration: 3, index: 1 },
  { type: "ban", team: "red", duration: 3, index: 1 },
  { type: "ban", team: "blue", duration: 3, index: 2 },
  { type: "ban", team: "red", duration: 3, index: 2 },
  { type: "pick", team: "blue", duration: 10, index: 0 },
  { type: "pick", team: "red", duration: 10, index: 0 },
  { type: "pick", team: "red", duration: 10, index: 1 },
  { type: "pick", team: "blue", duration: 10, index: 1 },
  { type: "pick", team: "blue", duration: 10, index: 2 },
  { type: "pick", team: "red", duration: 10, index: 2 },
  { type: "ban", team: "red", duration: 3, index: 3 },
  { type: "ban", team: "blue", duration: 3, index: 3 },
  { type: "ban", team: "red", duration: 3, index: 4 },
  { type: "ban", team: "blue", duration: 3, index: 4 },
  { type: "pick", team: "red", duration: 10, index: 3 },
  { type: "pick", team: "blue", duration: 10, index: 3 },
  { type: "pick", team: "blue", duration: 10, index: 4 },
  { type: "pick", team: "red", duration: 10, index: 4 },
  { type: "swap", team: "both", duration: 5, index: 0 },
];
