export const PHASE = [
  { type: "ban", team: "blue", duration: 30 },
  { type: "ban", team: "red", duration: 30 },
  { type: "ban", team: "blue", duration: 30 },
  { type: "ban", team: "red", duration: 30 },
  { type: "ban", team: "blue", duration: 30 },
  { type: "ban", team: "red", duration: 30 },
  { type: "pick", team: "blue", duration: 30 },
  { type: "pick", team: "red", duration: 30 },
  { type: "pick", team: "red", duration: 30 },
  { type: "pick", team: "blue", duration: 30 },
  { type: "pick", team: "blue", duration: 30 },
  { type: "pick", team: "red", duration: 30 },
  { type: "ban", team: "red", duration: 30 },
  { type: "ban", team: "blue", duration: 30 },
  { type: "ban", team: "red", duration: 30 },
  { type: "ban", team: "blue", duration: 30 },
  { type: "pick", team: "red", duration: 30 },
  { type: "pick", team: "blue", duration: 30 },
  { type: "pick", team: "blue", duration: 30 },
  { type: "pick", team: "red", duration: 30 },
  { type: "swap", duration: 60 },
];
